### ISSUE TITLE
libjpeg-dev missing for weboob installation

### ISSUE THREAD

**Issue by Toobian** [cozy/python_cozy_management#20] opened 2016-08-08 16:43 UTC
When I try to install weboob with cozy_management, somes errors with Pillow dependencies happened.

To solve that we need to install libjpeg-dev (Ubuntu 14.04.5 LTS).

Maybe cozy_management can install this dependency ?

**Comment by clochix** [comment] 2016-08-31 14:38
Ping @nledez

**Comment by nledez** [comment] 2016-09-13 11:58
The problem is on cozy package not this one.
By the way, it's fixed with another way soon.

**Closed as completed by nledez** 2016-09-13 11:58 UTC

**Comment by clochix** [comment] 2016-09-14 09:04
Thanks for reporting @Toobian ☺

**Comment by wangkesen** [comment] 2017-05-31 19:54
Got the same error today actually :(
